### ISSUE TITLE
AppStore resolution screenshots

### ISSUE THREAD

**Issue by danmindru** [parsecph/clobbr#163]
![1](https://user-images.githubusercontent.com/1515742/233194284-1adf6b80-ed77-4d89-a683-b812c7ce1415.png)
![2](https://user-images.githubusercontent.com/1515742/233194290-fbacba48-3c2c-4bc0-90c8-23c856873431.png)
![2a](https://user-images.githubusercontent.com/1515742/233194293-33721e7c-3fd8-405e-9b8b-97d23776b176.png)
![3](https://user-images.githubusercontent.com/1515742/233194297-1801eb2b-de0a-45d4-ad40-eba1d8a70d84.png)
![4](https://user-images.githubusercontent.com/1515742/233194300-7e411334-4469-4200-9036-ffa1668599e4.png)
![5](https://user-images.githubusercontent.com/1515742/233194302-6afd82bb-7375-493f-a115-d81b6d829c6c.png)
![6](https://user-images.githubusercontent.com/1515742/233194305-9872da14-0dc7-450b-8e23-bc9ae556a773.png)
![7](https://user-images.githubusercontent.com/1515742/233194308-fd2bc0a4-d0f0-4076-b034-dc49a1a28bea.png)

**Comment by danmindru** [comment]
![image](https://github.com/parsecph/clobbr/assets/1515742/8751337a-b18a-4429-8b8b-7333e647e561)

**Comment by mcnaveen** [comment]
LGTM 🫡
